---
repo-name: peripherals-apache-solr
categories:
- Database
- Storage
- Search
display-name: Apache Solr
manufacture: Apache
product: Solr
description: Solr is highly reliable, scalable and fault tolerant, providing distributed indexing, replication and load-balanced querying, automated failover and recovery, centralized configuration and more. Solr powers the search and navigation features of many of the world's largest internet sites.
